### PR TITLE
add all methods from amphora/files

### PR DESCRIPTION
**Pull request by nelsonpecora**
This PR adds all methods exported by `amphora/files`, allowing us to remove amphora as a dependency of our compilation code. https://github.com/clay/amphora/issues/469

Added methods:

* [x] `getYaml`
* [x] `getFiles`
* [x] `getFolders`
* [x] `fileExists`
* [x] `getComponents`
* [x] `getComponentPath`
* [x] `getComponentModule`
* [x] `getComponentPackage`
* [x] `isDirectory`
* [x] `tryRequire`
* [x] `readFilePromise`

### CODE REVIEW

**Comment by jonwinton** [comment]
We'll also need a `getLayoutModule` 😬

**Comment by nelsonpecora** [comment]
Are we going to support model.js and upgrade.js in layouts? (Also are we going to support layouts from npm?)

**Comment by jonwinton** [comment]
I know we need to support upgrades, models I can be persuaded to not support. I already wrote it in, but it's no big deal to pull it out.

**Comment by jonwinton** [comment]
Supporting models because of non-html renderers

**Review by jonwinton — APPROVED** [review]

**Pull request merged**
